version: '3.8'

services:
  frontend:
    build:
      context: ./KLTN_WEB
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./KLTN_WEB/.env

  backend:
    build:
      context: ./KTXM_CORE
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./KTXM_CORE/.env
